[package]
name = "rsweep"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1.32.0", features = ["full"] }
clap = { version = "4.4.6", features = ["derive"] }


[[test]]
name = "range_test"
path = "tests/range_test.rs"